# Generated by Django 2.2 on 2019-10-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recharge',
            name='expiry_date',
        ),
        migrations.AlterField(
            model_name='recharge',
            name='code',
            field=models.CharField(max_length=8),
        ),
    ]
