# Generated by Django 2.2 on 2019-10-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20191026_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='code',
            field=models.IntegerField(),
        ),
    ]
