# Generated by Django 2.2 on 2019-10-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mysolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=2000)),
                ('answer', models.CharField(max_length=2000)),
            ],
        ),
    ]
