# Generated by Django 2.2 on 2019-10-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysolution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysolution',
            name='answer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mysolution',
            name='question',
            field=models.CharField(max_length=100),
        ),
    ]
