# Generated by Django 2.2 on 2019-10-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysolution', '0003_auto_20191003_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='examsolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='mysolution',
        ),
    ]
