# Generated by Django 2.2 on 2019-10-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysolution', '0004_auto_20191003_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsolution',
            name='answer',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='examsolution',
            name='question',
            field=models.CharField(max_length=2000),
        ),
    ]
