# Generated by Django 2.2 on 2019-10-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysolution', '0005_auto_20191003_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsolution',
            name='grade',
            field=models.IntegerField(),
        ),
    ]
