# Generated by Django 2.2 on 2019-10-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysolution', '0006_auto_20191018_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsolution',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='examsolution',
            name='grade',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='examsolution',
            name='question',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='examsolution',
            name='subject',
            field=models.TextField(blank=True),
        ),
    ]
