# Generated by Django 2.2.7 on 2020-02-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysolution', '0007_auto_20191019_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask_Qus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qus', models.TextField(blank=True)),
            ],
        ),
    ]
