# Generated by Django 2.2 on 2019-10-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytutorial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution_videos',
            name='video',
        ),
        migrations.AddField(
            model_name='solution_videos',
            name='video_link',
            field=models.URLField(null=True),
        ),
    ]
