# Generated by Django 2.2.7 on 2020-02-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('desp', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='books')),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
