# Generated by Django 2.2.7 on 2020-02-12 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebook',
            old_name='file',
            new_name='book',
        ),
    ]
