# Generated by Django 2.2.7 on 2020-02-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0002_auto_20200212_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebook',
            old_name='book',
            new_name='ebook',
        ),
    ]
