# Generated by Django 2.2.7 on 2020-02-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0003_auto_20200212_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='ebook',
            field=models.FileField(upload_to='../media'),
        ),
    ]
